### ISSUE TITLE
php throws error

### ISSUE THREAD

**Issue by gnurbs** [jciolek/shotwell-merge#2]
Hi,

sorry for the shitty summary, but it's quite fitting:

```
$ php5 run.php -s ~/shotwell.db 
Merging VideoTable...PHP Warning:  SQLite3::prepare(): Unable to prepare statement: 1, near ")": syntax error in /home/arian-debian/src/shotwell-merge/Merge.php on line 62
PHP Fatal error:  Call to a member function bindValue() on boolean in /home/arian-debian/src/shotwell-merge/Merge.php on line 81
```

debian stretch on amd64 here, relevant packages:

```
ii  shotwell        0.22.0-2     amd64
ii  shotwell-common 0.22.0-2     all
ii  php5-cli        5.6.12+dfsg-1 amd64
ii  php5-sqlite     5.6.12+dfsg-1 amd64
```

thanks for the script though - it's just what I need (If it worked...)

**Comment by jciolek** [comment]
Hi,

Thanks for trying to use it :) I had a quick look. Basically, at the moment you need to copy the db you want to add to to `result/photo.db`. 

Cheers,
Jacek

**Comment by gnurbs** [comment]
Hi Jacek,

great, worked for me now! Would be great if you could correct the readme - this is one of the first google results for "shotwell database merge" and about the only helpful one :)

Cheers, Arian
